---
dist: xenial
sudo: required
language: python
python: "3.7"

env:
  - MOLECULE_DISTRO=centos6
  - MOLECULE_DISTRO=centos7

services:
  - docker

before_script:
  - cd ../
  - mv ansible-role-bootstrap daixijun.bootstrap
  - cd daixijun.bootstrap

install:
  - pip install ansible molecule docker
  - pip install --upgrade testinfra

script:
  - molecule test

notifications:
  email: false
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
