---
- name: System upgrade
  package:
    name: "*"
    update_cache: yes
    state: latest
  tags:
    - skip_ansible_lint
  when: bootstrap_upgrade

- name: Install package tzdata
  package:
    name: tzdata
    state: present

- name: Symlink /etc/localtime
  file:
    src: /usr/share/zoneinfo/{{ bootstrap_timezone }}
    dest: /etc/localtime
    force: true
    state: link

- name: Change /etc/timezone
  copy:
    content: "{{ bootstrap_timezone }}"
    dest: /etc/timezone

- name: Update the hostname
  hostname:
    name: "{% if bootstrap_hostname %}{{ bootstrap_hostname }}{% else %}{{ inventory_hostname }}{% endif %}"

- name: Add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ bootstrap_hostname }} {{ inventory_hostname }}{% if inventory_hostname != inventory_hostname_short %} {{ inventory_hostname_short }}{% endif %}"  # noqa 204
    regexp: "^{{ ansible_default_ipv4.address }}"
    state: present
  ignore_errors: true

- name: PAM limits
  pam_limits:
    domain: "*"
    limit_item: nofile
    limit_type: "-"
    value: '65535'

- name: Render sysctl
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    backup: true
  register: sysctl_status

- name: Apply sysctl
  command: /sbin/sysctl -p
  ignore_errors: true
  when:
    - sysctl_status is changed
